plugins {
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.146'
}

version = "${project.minecraft_version}-neoforge-${project.mod_version}"
group   = project.maven_group
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenLocal()
    maven {
        url = "https://maven.neoforged.net/releases"
    }
    maven { url = "https://api.modrinth.com/maven"; content { includeGroup "maven.modrinth" } }
    maven { url = "https://cursemaven.com"; content { includeGroup "curse.maven" } }
    maven { name = "Progwml6"; url = "https://dvs1.progwml6.com/files/maven/" }
    maven { name = "BlameJared"; url = "https://maven.blamejared.com/" }
    maven { name = "ModMaven"; url = "https://modmaven.dev" }
}


neoForge {
    version = project.neo_version
    accessTransformers.from('src/main/resources/META-INF/accesstransformer.cfg')
    runs {
        client {
            client()
            gameDirectory = project.file('run')
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
        }
        server {
            server()
            gameDirectory = project.file('run')
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
        }
    }
    mods { the_last_sword { sourceSet sourceSets.main } }
}

dependencies {
    implementation("net.eca:eca:1.1.8-fix-fix") { transitive = false }
    //implementation files("lib/epic-core-api-1.1.8-fix-fix_dev.jar")
    implementation "curse.maven:geckolib-388172:8893490"
    implementation "curse.maven:curios-309927:6529130"

    implementation "curse.maven:jei-238222:9068136"
    implementation "curse.maven:just-enough-resources-jer-240630:6506298"
    //implementation "curse.maven:just-enough-characters-250702:7411324"
    implementation "curse.maven:jade-324717:8591319"
    implementation "curse.maven:lendercataclysm-551586:8931182"
    implementation "curse.maven:lionfish-api-1001614:8345326"
    implementation "curse.maven:playeranimator-658587:7389814"
    implementation "curse.maven:irons-lib-1492763:8973642"
    implementation "curse.maven:irons-spells-n-spellbooks-855414:8680204"
    implementation "curse.maven:touhou-little-maid-355044:8061852"
    implementation "curse.maven:farmers-delight-398521:8765184"
    implementation "curse.maven:spark-361579:6225208"
}

processResources {
    inputs.property 'mod_version', project.mod_version
    filesMatching('META-INF/neoforge.mods.toml') { expand 'mod_version': project.mod_version }
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
tasks.jar { duplicatesStrategy = DuplicatesStrategy.EXCLUDE }
